server:
  port: 8051
eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:

spring:
  application:
    name: gateway-spring
  profiles:
    active: production
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
